name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: mkdir public
      - uses: docker://pandoc/latex:2.9
        with:
          args: -f gfm -t revealjs -s Documentation/Sprint1/sprint1.md -o public/sprint1.html -V theme=dracula --slide-level=2
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
